export enum BuildingType {
    SHIPYARD = "SHIPYARD",
    MINING_STATION = "MINING_STATION",
    REFINERY = "REFINERY",
    COLONY = "COLONY",
    POWER_PLANT = "POWER_PLANT",
    ACADEMY = "ACADEMY",
    RESEARCH_LAB = "RESEARCH_LAB",
    RECRUITER = "RECRUITER",
    TRADING_STATION = "TRADING_STATION"
}
